version: "3.8"
services:
  frontend:
    image: hiruniwijendrasinhe/alertfy_frontend:latest
    container_name: frontend_c
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/my-app/.env
    depends_on:
      - backend

  backend:
    image: hiruniwijendrasinhe/alertfy_backend:latest
    container_name: backend_c
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env
    # No 'depends_on' for db, because it's external (XAMPP)

# Remove the db service entirely
