version: "3.8"
services:
  frontend:
    image: hiruniwijendrasinhe/alertfy_frontend:latest
    container_name: frontend_c
    ports:
      - "3000:80"
    env_file:
      - ./frontend/my-app/.env
    depends_on:
      - backend

  backend:
    image: hiruniwijendrasinhe/alertfy_backend:latest
    container_name: backend_c
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: incident_management
      MYSQL_USER: nodeuser
      MYSQL_PASSWORD: nodepass
    ports:
      - "3306:3306"
